export const Z_INDEX = {
  SIDEBAR_CLOSED: 25,
  MOBILE_TOOLBAR: 30,
  SCROLL_TO_BOTTOM: 31,
  MOBILE_ADD_BTN: 35,
  SIDEBAR_BACKDROP: 36,
  SIDEBAR_OPEN: 38,
  BS_OVERLAY: 9998,
  BS_CONTENT: 9999,
} as const;
